### ISSUE TITLE
Support breakpoints

### ISSUE THREAD

**Issue by pke** [Microsoft/vscode-npm-scripts#18] opened 2016-08-08 14:27 UTC
Would be nice if this extension would respect breakpoints set in the `npm` script being run.

**Comment by jdnichollsc** [comment] 2016-08-09 15:32
+1

**Comment by egamma** [comment] 2016-08-09 21:18
This is a duplicate of https://github.com/Microsoft/vscode/issues/2726#issuecomment-180318655

**Closed by egamma** 2016-08-09 21:18 UTC
