### ISSUE TITLE
VSCode 1.31 broke npm shortcuts

### ISSUE THREAD

**Issue by heihachi88** [Microsoft/vscode-npm-scripts#72] opened 2019-02-08 05:24 UTC
Before 1.31 i could press ⌘+R, Shift+R to run NPM scripts defined in my package.json, but now it doesn't work, i have to call command palette ⌘+Shift+P, only then i can use shortcut ⌘+R, Shift+R

**Comment by egamma** [comment] 2019-02-08 11:18
I cannot reproduce this. Can you check in the keybindings editor whether you have customized the keybindings for ⌘+R

**Comment by heihachi88** [comment] 2019-02-08 11:21
It's not a custom keybinding:

![image](https://user-images.githubusercontent.com/5739191/52475477-c8449400-2bc5-11e9-8225-0a260b5c8b01.png)

![image](https://user-images.githubusercontent.com/5739191/52475511-e4483580-2bc5-11e9-80f1-2efdd7c3a6fc.png)

**Comment by egamma** [comment] 2019-02-08 11:23
In the editor search wheter ⌘+R is no bound to another command.

**Comment by heihachi88** [comment] 2019-02-08 11:24
No, it's not, it worked today just before 1.31 update applied...

**Comment by egamma** [comment] 2019-02-08 11:26
Can you attach what you get when you search for cmd+r in the keybindings editor

<img width="486" alt="image" src="https://user-images.githubusercontent.com/172399/52475726-b13d7c00-2b9c-11e9-9886-559c5c88a0cf.png">

**Comment by heihachi88** [comment] 2019-02-08 11:28
![image](https://user-images.githubusercontent.com/5739191/52475792-de9f1f80-2bc6-11e9-8471-eaf2a1d2f0d8.png)

**Comment by heihachi88** [comment] 2019-02-10 15:12
So, have you reproduced this bug?

**Comment by egamma** [comment] 2019-02-10 20:11
Works for me (see the attached movie). Also searched in the vscode issues, but I could not find similar issues. Can you try to assign another chording keybinding and check whether the issues is cmd+R specific.

![keybinding](https://user-images.githubusercontent.com/172399/52538864-f964c600-2d77-11e9-8a31-6d61bcd95874.gif)

**Comment by heihachi88** [comment] 2019-02-10 20:13
Well, i've tried ⌘K, ⌘S, when i pressed ⌘K nothing happens, i don't see the text in the bottom bar "⌘K was pressed, waiting for second key of chord"

**Comment by egamma** [comment] 2019-02-10 20:29
Do the ⌘K keybindings work for you? Do you have a special keyboard?

In general this cannot be an issue with this extension. This looks like a VS Code keyboard issue. Please consult this trouble shooting guide https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by heihachi88** [comment] 2019-02-11 05:14
> Do the ⌘K keybindings work for you? Do you have a special keyboard?
Nope, i'm using built-in macbook pro 13"s keyboard.

**Comment by heihachi88** [comment] 2019-02-11 06:11
@egamma, try to open Terminal window and focus it, then use ⌘R, Shift+R or ⌘K, ⌘S

**Comment by egamma** [comment] 2019-02-11 07:19
@heihachi88 thank you for providing the reproducable case. 

This is issue https://github.com/Microsoft/vscode/issues/22211, which has been closed as designed.

**Closed by egamma** 2019-02-11 07:19 UTC
Labels: needs more info

**Comment by heihachi88** [comment] 2019-02-11 12:00
But how it worked in a previous versions?

**Comment by egamma** [comment] 2019-02-11 16:48
Can you reproduce that this scenario worked in 1.30 when the terminal has focus?
