### ISSUE TITLE
I can't run the task by click this .

### ISSUE THREAD

**Issue by shanliangdeYWJ** [microsoft/vscode-npm-scripts#99] opened 2020-03-05 09:04 UTC
![2020-03-05_170859](https://user-images.githubusercontent.com/49124030/75965621-06fd6880-5f04-11ea-9b67-784c88dd0182.png)

I used run task by click this ,since delete some vscode snippet suport extentions by mistakes , I update my vscode to 1.42.0 . Now I can't run my task througth this way. Although I can run tasks in  another way, I want to know this way

I copy the extension in the update package to the extension in the old directory

**Comment by egamma** [comment] 2020-03-31 08:43
Duplicate of https://github.com/microsoft/vscode/issues/90855, will be fixed in 1.43.

**Closed by egamma** 2020-03-31 08:43 UTC
