### ISSUE TITLE
Output panel encoding

### ISSUE THREAD

**Issue by dmaglio** [Microsoft/vscode-npm-scripts#58] opened 2018-03-26 08:50 UTC
```
ng serve --host localhost --port 3000 --serve --open

** NG Live Development Server is listening on localhost:3000, open your browser on http://localhost:3000/ **
webpack: wait until bundle finished: /
[0mDate: [1m[37m2018-03-26T08:40:49.599Z[39m[22m[0m
[0mHash: [1m[37m5c832b61970350d91df4[39m[22m[0m
[0mTime: [1m[37m31511[39m[22mms[0m
[0mchunk {[1m[33minline[39m[22m} [1m[32minline.bundle.js[39m[22m (inline) 3.85 kB [1m[33m[entry][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33mmain[39m[22m} [1m[32mmain.bundle.js[39m[22m (main) 871 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33mpolyfills[39m[22m} [1m[32mpolyfills.bundle.js[39m[22m (polyfills) 549 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33mscripts[39m[22m} [1m[32mscripts.bundle.js[39m[22m (scripts) 367 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33mstyles[39m[22m} [1m[32mstyles.bundle.js[39m[22m (styles) 2.66 MB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33mvendor[39m[22m} [1m[32mvendor.bundle.js[39m[22m (vendor) 27.7 MB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
```

**Comment by dmaglio** [comment] 2018-03-26 08:51
if i run into terminal the encoding is correct

**Comment by egamma** [comment] 2018-03-28 07:09
@dmaglio this is caused by a tool not emitting UTF-8 and there is currently no support for defining the encoding used in the output channel in VS Code. I intend to deprecate using the output channel for ouput and only support to use the terminal for output, which can be done using the setting `npm.runInTerminal`. 

In addition the recommended way to run npm-scripts is the recently added support for running npm script as tasks ('Tasks>Run Task'). Can you give this a try and let me know whether this covers your needs.

I´ll therefore close this issue.

**Closed by egamma** 2018-03-28 07:09 UTC
